// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <stdio.h>
#include <stdlib.h>

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_t.h"

// This is the function that the host calls. It prints
// a message in the enclave before calling back out to
// the host to print a message from there too.
void enclave_helloworld()
{
    int *n = rand() % 255 ;
    int *pro  ;
    fprintf(stdout , "What is your guess ???   :   ") ;
    scanf("%d" , pro) ;
    fprintf(stdout , "\n") ;
    while (*pro != *n) {
        fprintf(stdout , "Wrong guess. Try again   :   ") ;
        scanf("%d" , pro) ;
        fprintf(stdout , "\n") ;
    }

    // Call back into the host
    oe_result_t result = host_helloworld();
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "Call to host_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
    }
}
